

export const ADD_QUESTIONNAIRE = 'ADD_QUESTIONNAIRE';

export const SORT_TABLE = 'SORT_TABLE';

export const CHANGE_SELECT_TYPE = 'CHANGE_SELECT_TYPE';

export const ADD_QUESTION = 'ADD_QUESTION';

export const TEXT_EDIT = 'TEXT_EDIT';

export const SAVE_EDIT = 'SAVE_EDIT';

export const ADD_OPTION = 'ADD_OPTION';

export const DELETE_QUESTION = 'DELETE_QUESTION';

export const COPY_QUESTION = 'COPY_QUESTION';

export const SHIFT_QUESTION = 'SHIFT_QUESTION';

export const TEXT_REQUIRED = 'TEXT_REQUIRED';

export const PUBLISH_QUESTIONNAIRE = 'PUBLISH_QUESTIONNAIRE';
			
export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE';

export const EDIT_QUESTIONNAIRE = 'EDIT_QUESTIONNAIRE';

export const REMOVE_QUESTIONNAIRE = 'REMOVE_QUESTIONNAIRE';

export const FILL_QUESTIONNAIRE = 'FILL_QUESTIONNAIRE';

export const FILL_RADIO = 'FILL_RADIO';

export const FILL_CHECKBOX = 'FILL_CHECKBOX';

export const SUBMIT_QUESTIONNAIRE = 'SUBMIT_QUESTIONNAIRE';

export const CHECK_DATA = 'CHECK_DATA';

export const FILL_TEXT = 'FILL_TEXT';

export const SELECT_TIME = 'SELECT_TIME';